#! /usr/bin/env python3

# dox++
# Copyright 2020, Cris Luengo
# Based on cldoc: Copyright 2013-2018, Jesse van den Kieboom
#
# This file is part of dox++.  dox++ is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import argparse
import json
import doxpp


parser = argparse.ArgumentParser(description='Clang based documentation generator.')
parser.add_argument('-g', action='store_true', help='generate a default configuration file')
parser.add_argument('config_file', nargs='?', default='dox++config', help='name of the configuration file')
args = parser.parse_args()

# Generate configuration file if requested, then quit
if args.g:
    doxpp.config.generate(args.config_file)
    exit(0)

# Processing options
config = doxpp.config.read(args.config_file)

doxpp.log.setLevel(config['log'].get('level', 'warning'))  # the default value

options = {
    'code_formatting': config['json'].get('use typewriter font', 'no'),
    'tab_size': int(config['input'].get('tab size','4'))
}

# Process files
data = doxpp.buildtree.buildtree(
    config['input'].get('root directory', '.'),
    config['input'].get('header files', '*.h *.hpp'),
    config['input'].get('markdown files', '*.md'),
    config['clang'].get('compiler flags', ''),
    config['clang'].get('include directories', ''),
    options
)

# Write JSON file
filename = config['json'].get('filename', 'dox++out.json')
if config['json'].get('formatting', 'compact') == 'readable':
    format = {'indent': 2}
else:
    format = {'separators': (',', ':')}
with open(filename, 'w') as output_file:
    output_file.write(json.dumps(data, **format))
